version: '3.5'
services:

  kibana:
    image: ${KIBANA_IMAGE}
    container_name: 'kibana'
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    # Inside Kibana logging goes to stdout by default
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
    ports:
      - 5601:5601
    networks:
     - 'sylius'
    restart: 'always'
    depends_on:
      - elasticsearch
