version: '3.5'
services:

  php:
    volumes:
      - '../../${DEPLOY_PATH}:${STACK_PATH}/${DEPLOY_PATH}'
      - '../../sylius/data/maintenance:${STACK_PATH}/${MAINTENANCE_PATH}'
      # DON'T CHANGE: This is composer default env var to set cache path
      - '../volumes/php/composer:/home/${LOCAL_USER}/.composer'
      # DON'T CHANGE: This is yarn default env var to set cache path
      - '../volumes/php/yarn-cache:/home/${LOCAL_USER}/.yarn-cache'
      # SSH Keys (Needed by deployer to deploy to remote server)
      - '../../${SSH_KEYS_PATH}:${STACK_PATH}/${SSH_KEYS_PATH}'
    environment:
      # DON'T CHANGE: This is composer default env var to set cache path
      COMPOSER_CACHE_DIR: '/home/${LOCAL_USER}/.composer/cache'
      # DON'T CHANGE: This is yarn default env var to set cache path
      YARN_CACHE_FOLDER: '/home/${LOCAL_USER}/.yarn-cache'

      # Needed by deployer to deploy app
      APP_CURRENT_RELEASE_PATH: ${STACK_PATH}/${APP_CURRENT_RELEASE_PATH}
      APP_DEPLOYMENT_PATH: ${STACK_PATH}/${APP_DEPLOYMENT_PATH}
      APP_ENV: ${APP_ENV}
      APP_REPO: ${APP_REPO}
      APP_BRANCH: ${APP_BRANCH}
      DEPLOY_PATH: ${STACK_PATH}/${DEPLOY_PATH}
      GITHUB_OAUTH_TOKEN: ${GITHUB_OAUTH_TOKEN}
      HOST_IP: ${HOST_IP}
      LOCAL_USER_UID: ${LOCAL_USER_UID}
      MAINTENANCE_PATH: ${STACK_PATH}/${MAINTENANCE_PATH}
      POPULATE_DATABASE: ${POPULATE_DATABASE}
      REMOTE_IDENTITY: ${REMOTE_IDENTITY}
      REMOTE_PORT: ${REMOTE_PORT}
      REMOTE_USER: ${REMOTE_USER}
      SSH_KEYS_PATH: ${STACK_PATH}/${SSH_KEYS_PATH}
      STACK_REPO: ${STACK_REPO}
      USE_SUDO: ${USE_SUDO}
      VERBOSITY: ${VERBOSITY}
      WITH_ELASTICSEARCH: ${WITH_ELASTICSEARCH}
      WITH_VARNISH: ${WITH_VARNISH}
