version: '3.5'
services:

  php:
    volumes:
      # Xdebug extension config file
      - '../images/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    environment:
      # php.ini
      PHP_XDEBUG_ENABLE: ${PHP_XDEBUG_ENABLE}
      PHP_XDEBUG_HOST_IP: ${PHP_XDEBUG_HOST_IP}
      PHP_XDEBUG_REMOTE_PORT: ${PHP_XDEBUG_REMOTE_PORT}
